import Link from 'next/link';
import {loadStrategic} from '@/lib/strategicFutures';
import {editionMode} from '@/lib/readerEdition';
import {FuturesExplorer} from './FuturesExplorer';
export function StrategicStudy({paper=false}:{paper?:boolean}){
 const data=loadStrategic(editionMode());
 return <main id="main-content" className="strategic-study" data-author-status={data.humanReview==='author_reviewed'?'approved':'pending'}>
  <section className="strategic-opening"><div><h1>When does an AI lead become lasting power?</h1><p className="strategic-deck">Advanced AI, the US–China relationship, and possible worlds through 2040.</p><div className="strategic-entry-actions"><a className="reader-button" href="#explorer">Change the conditions</a> <Link href="/paper">Read / print the narrative</Link></div><p>{data.author.opening}</p><p>{data.author.judgment}</p><p className="edition-note">6 September 2026 · private-review prototype · draft personal copy for Jinhua’s edit. GitHub materials are public.</p></div><aside><h2>Three clocks, no fixed winner.</h2><ol className="strategic-clocks"><li><strong>Advance</strong><span>Does AI improve the process of making the next AI?</span></li><li><strong>Spread</strong><span>Who gets usable capability before exclusivity pays?</span></li><li><strong>Convert</strong><span>Which firms and institutions turn it into consequential work?</span></li></ol><p>These processes can change one another. A technological lead, control over deployment and broad social benefit can end up in different hands.</p></aside></section>
  <section className="strategic-start"><h2>Start with the strongest compounding case.</h2><p>Imagine a US-based frontier coalition gets a lead in research-relevant AI. It protects that access, repeatedly uses AI to improve its successors, and brings validated process changes into physical deployment. Give it those conditions before asking what could undo the advantage. The initial national lead is a stipulation, not a ranking.</p><p>The canvas stays beside the unfolding argument. Change the conditions or choose a proposed future, then compare it with the pinned starting case.</p></section>
  <FuturesExplorer data={data} paper={paper}/>
  <section className="strategic-evidence-intro"><h2>The starting evidence points in more than one direction.</h2><div>{data.sources.slice(0,6).map(s=><article key={s.id} data-strategic-source={s.id} data-strategic-review={s.reviewStatus}><h3><Link href={`/assumptions#${s.id}`}>{s.title}</Link></h3><p>{s.claim}</p><p className="figure-note">{s.kind==='official_intent'?'Official programme intent':s.kind==='report'?'Originating report':'Source analysis'} · {s.organization} · {s.publicationDate??s.version}</p></article>)}</div><p>Neither national programme fits a simple “US invents, China deploys” story. Their intentions overlap; which actors deliver, at what cost and for whose benefit is an empirical question. <Link href="/assumptions#source-trace">Read the exact limits, including the draft Chinese translation.</Link></p></section>
  <section className="strategic-ending"><h2>Power for whom?</h2><p>{data.author.closing}</p><p>The race branch can concentrate productive and strategic capability. Earlier diffusion can spread access without spreading ownership. A public mission can turn assurance into a condition for useful deployment, but verification can fail and priorities have costs. Conflict or loss of effective control can break the entire benign trajectory. None of these possibilities is settled by a workplace productivity percentage.</p><p className="edition-note">Draft author interpretation. No scenario probability or publication assent recorded.</p><p><Link href="/work">Supporting study: what AI changed in actual work</Link> · <Link href="/assumptions#rival-accounts">AI 2027, Plan A and AI as Normal Technology</Link> · <Link href="/about">Authorship</Link></p></section>
 </main>;
}
