import {z} from 'zod';
export const futureInputSchema=z.object({research:z.enum(['compounding','bounded']),diffusion:z.enum(['restricted','broad']),deployment:z.enum(['redesign','existing']),settlement:z.enum(['race','broad','compact','rupture'])}).strict();
export type FutureInput=z.infer<typeof futureInputSchema>;
export const DEFAULT_FUTURE:FutureInput={research:'compounding',diffusion:'restricted',deployment:'redesign',settlement:'race'};
export const priorities={
 race:['Frontier experiments','Selected deployments','Access and assurance'],
 broad:['Deployment and public access','Assurance and worker adjustment','Frontier experiments'],
 compact:['Verification and agreed missions','Permitted deployments','Unrestricted frontier experiments'],
 rupture:['Continuity and control recovery','Essential services','New experiments and expansion']
} as const;
/** Qualitative scenario rules. No calendar integration, causal coefficients,
 * national scores, resource quantities or probabilities are computed. */
export function deriveFuture(raw:FutureInput){
 const a=futureInputSchema.parse(raw);
 const interrupted=a.settlement==='rupture';
 const shared=a.diffusion==='broad';
 const compact=a.settlement==='compact';
 const loop=a.research==='compounding'&&!interrupted;
 const redesign=a.deployment==='redesign'&&!interrupted;
 const transmission=a.settlement==='broad'||compact;
 const effectiveLoop=loop?(compact?'mission-limited':'reinforcing'):'bounded';
 const power=interrupted?'Advantage becomes unassessable':compact?'Access governed by a contested compact':shared?'Exclusive leverage weakens; deployment still matters':loop?'A protected research lead can compound':'A lead persists without assumed takeoff';
 const production=interrupted?'Expansion interrupted':redesign?'A different physical pathway becomes available':'Integration and qualification remain separate tasks';
 const households=interrupted?'Household gains cannot be carried forward':transmission?'A benefit channel is stipulated, not guaranteed':'Output can grow while gains remain concentrated';
 const us=interrupted?'Continuity uncertain':compact?'Frontier discretion constrained':shared?'Initial lead; exclusivity erodes':loop?'Protected reinvestment option':'Bounded initial advantage';
 const china=interrupted?'Continuity uncertain':shared?'Relevant usable capability accessible':'Local R&D; restricted external access';
 const global=interrupted?'Trade and cooperation disrupted':shared?'More supplier choice; serving costs remain':'Access depends on licensing and bargaining';
 const research=interrupted?'Loop interrupted':effectiveLoop==='mission-limited'?'Feedback within permitted work':loop?'Verified gains feed the next cycle':'Useful gains; no assumed recursive loop';
 const political=compact?'Verification + public missions':a.settlement==='broad'?'Procurement + benefit sharing':interrupted?'Recovery + political stress':'Owners + selected state users';
 const phases=[
  {window:'2026 → opening premise',title:'A lead worth protecting',text:'Stipulate a US-based frontier coalition with an initial advantage in the capabilities relevant to this story. Chinese developers pursue their own systems; firms in other countries can buy, adapt or bargain for access. This is a chosen starting premise, not a measured ranking of today’s models.'},
  {window:'Before 2030 · stipulated window',title:interrupted?'The benign branch breaks':loop?'Research changes the next research cycle':'Useful systems without a closed loop',text:interrupted?'Conflict, coercive disruption or loss of effective control interrupts research and cross-border supply. The rules withdraw claims about orderly compounding and household gains; they do not estimate the damage or declare either state the winner.':loop?`Assume the systems help researchers generate, test and retain improvements across successive model-development cycles. This goes beyond the bounded AlphaEvolve report: repetition, secure reinvestment and reliable evaluation are additional premises. ${compact?'A verified agreement restricts unrestricted frontier experimentation; the feedback is redirected into permitted work.':'Assume these gains free scarce researcher time or computing work for the next cycle, and that the owners choose to reinvest rather than consume the savings. Better systems could help design algorithms, experiments and equipment; those improvements then support further research. This is the proposed compounding mechanism, not a rate inferred from one reported gain.'}`:'Assume AI helps with particular research tasks, but improvements do not reliably accelerate the full cycle of developing successors. This leaves substantial applications possible without assuming an intelligence explosion.'},
  {window:'The 2030s · conditional development',title:redesign?'Change the route, not only the pace':'Build through the existing route',text:interrupted?'Institutions must restore dependable control and essential services before this development path can resume. Reopening trade or research cooperation would require a new assumption, not a cosmetic reset of a growth curve.':redesign?'Assume AI-assisted engineering produces validated changes to industrial integration, laboratory operations and equipment design. Dedicated capital, qualified hardware and operating staff are still required. The changed network includes deployment feedback into design: the scenario can create new ways around today’s constraints rather than making every future wait at the same queue.':'Useful designs enter existing procurement, qualification and integration processes. These tasks can improve, but this branch supplies no new integrated pathway. Chinese manufacturers, US operators and third-country suppliers would have to demonstrate delivered performance in their own settings.'},
  {window:'Toward 2040 · conditional implications',title:power,text:interrupted?'Neither national advantage nor human flourishing can be extrapolated through this interruption. Security, legitimacy and human control are part of whether the trajectory remains meaningful.':compact?'The strongest version of this branch makes compliance inspectable, rewards participation and preserves permitted useful research. It spends scarce attention on verification and public missions instead of an unrestricted race. Covert projects, defections or disputed inspections could unravel it; a treaty announcement is not that capability.':shared?`Usable capability spreads before the initial coalition can consolidate exclusive control. Chinese developers and third-country adopters gain options; model developers can still earn rents, and a residual research frontier may remain strategically important. ${transmission?'Procurement, competition, access and worker adjustment are stipulated to transmit some gains. Their success must be tested through household and service outcomes.':'Ownership can remain concentrated even when model weights cross borders. States and firms may become more productive while workers’ bargaining power, household income or legitimacy fall behind.'}`:`Restricted access plus ${loop?'repeated research feedback':'bounded improvements'} preserves an option for the initial coalition to concentrate scientific and strategic capacity. It could set access terms for important research tools, choose which discoveries to develop, and give selected public agencies earlier access to useful systems. Those are potential bargaining advantages, not a measured military edge. Allied suppliers retain bargaining power; dependence has not disappeared. ${transmission?'Broad-benefit institutions are assumed to channel part of the output into services and household gains.':'The first beneficiaries are the owners and selected institutions controlling deployment. Public welfare does not follow automatically from geopolitical leverage.'}`}
 ];
 const repeatEvidence='Successive independently evaluated improvements improve the end-to-end process of developing useful successors.';
 const boundedEvidence='Gains stay confined to easily scored tasks, fail to reproduce, or consume the savings in evaluation and integration.';
 const diffusionEvidence='Affordable, reliable substitutes reach relevant users before the leader can consolidate the selected advantage.';
 const exclusionEvidence='The decisive research/security capability remains unavailable, or serving and qualified hardware prevent effective use.';
 const checkpoints=[
  {name:'Does the research loop repeat?',supports:a.research==='compounding'?repeatEvidence:boundedEvidence,weakens:a.research==='compounding'?boundedEvidence:repeatEvidence,sourceIds:['sf-alpha','sf-ai2027','sf-normal']},
  {name:'Does useful capability arrive before exclusivity pays?',supports:shared?diffusionEvidence:exclusionEvidence,weakens:shared?exclusionEvidence:diffusionEvidence,sourceIds:['sf-deepseek','sf-asml']},
  {name:interrupted?'Does continuity break?':transmission?'Do institutions deliver their side of the bargain?':'Does control stay concentrated?',supports:interrupted?'Verified disruption prevents dependable operation, exchange or effective human control.':compact?'Monitoring finds meaningful violations; parties accept inspection costs and preserve permitted useful work.':transmission?'Evidence connects deployment to delivered industrial/public services and separately to household outcomes.':'Ownership, procurement and bargaining channel gains toward a limited group while broader household gains lag.',weakens:interrupted?'Dependable control and essential cooperation are restored; rebuilding can support a new branch.':compact?'Covert development, defection or disputes overwhelm verification.':transmission?'Production grows but ownership, access or adjustment failures interrupt the benefit channel.':'Reliable evidence shows widely shared gains through prices, wages, services or access.',sourceIds:['sf-china','sf-us','sf-ai2040']}
 ];
 return {input:a,interrupted,shared,loop,redesign,effectiveLoop,power,production,households,us,china,global,research,political,phases,checkpoints,priorities:priorities[a.settlement],ruleIds:['research','diffusion','deployment','settlement']};
}
export type FutureResult=ReturnType<typeof deriveFuture>;
export function changedAssumptions(before:FutureInput,after:FutureInput){return (Object.keys(before) as (keyof FutureInput)[]).filter(k=>before[k]!==after[k]);}
