import Link from 'next/link';
export const metadata={title:'Method and assumptions'};
export default function Methods(){
  return <main id="main-content" className="reader-document narrow-document">
    <h1>Trace a future without disguising its premises.</h1>
    <p className="document-intro">The flagship connects capability progress, international diffusion and national/social consequences through explicit scenario assumptions. Historical task studies support particular mechanisms; they do not determine the future.</p>
    <h2>The strategic construction</h2><p>Four categorical inputs operate explicit qualitative rules. Research feedback, diffusion ordering and validated process change alter the network; the political bargain changes priorities and benefit channels. Longer chains are separately labelled scenario constructions, not upgrades to the eight accepted coupling dispositions. No growth rate, national aggregate or probability is calculated. The existing external-scenario crosswalk and six shared premise dimensions remain records.</p><p><Link href="/assumptions">Read every rule and its source or stipulated basis</Link>. Dates within the construction are illustrative windows. A valid forecast would need a resolution condition, window, source and actual author judgment; none is activated here.</p><h2>Where the argument comes from</h2>
    <p>Productivity research already studies the investments around a technology. The existing related-work register includes <a href="https://www.bis.org/publ/work1325.htm">Aldasoro and colleagues’ research on AI adoption and complementary investment</a> (BIS Working Paper 1325), and <a href="https://doi.org/10.2307/jj.12228596">Jeffrey Ding’s account of technological diffusion and national power</a>. This edition’s contribution is its cross-case synthesis and explicit attribution questions. Adding serial durations, taking the maximum of independent parallel durations, and finding the minimum station capacity are standard duration/capacity reasoning. They are not a new estimator, a new productivity theory or an empirical calibration.</p>
    <h2>How to read the supporting work evidence</h2>
    <dl className="evidence-details">
      <div><dt>Reported use</dt><dd>ECB intensity, Census function breadth and Eurostat firm-size adoption retain their survey universes. The Census comprehensive-adopter share is model-derived. The NBS context remains unplotted and translation-restricted. Higher adoption is not itself a welfare objective.</dd></div>
      <div><dt>Operational evidence</dt><dd>QJE compares assistant access with no access through staggered rollout and difference-in-differences; comparable counterfactual trends matter. METR randomizes task-level access in a selected early-2025 setting. Neither isolates a weaker-to-stronger model upgrade. Their differences do not identify workflow design as the cause: populations, tasks, tools, dates and estimators differ.</dd></div>
      <div><dt>Conditional arithmetic</dt><dd>Project duration is a serial sum or parallel maximum, plus optional incremental work after the required tasks. The added work defaults to zero and is not inferred from METR. Quality is held constant by assumption. Repeated output is a separate minimum-capacity model; project overhead never enters it. There is no estimated empirical bottleneck, queue, variability or quality model.</dd></div>
      <div><dt>Transfer and attribution</dt><dd>TCV demonstrates a specialist learned controller, not a chat-model upgrade. Its simulator, physical feedback loop and post-experiment evaluation are distinguished. Plant qualification and national value capture require other evidence. The actor map assigns roles, not financial shares; its arrows carry no effect-size meaning.</dd></div>
    </dl>
    <h2>How the operational bars were drawn</h2>
    <p>Each panel sets its own comparison reference to 100 and applies the reported relative estimate: 100 × (1 + estimate/100). Thus 15% becomes 115 on the resolutions/hour index, and 19% becomes 119 on the task-time index. These are transformations of estimates, not observed group means or a common metric. METR’s historical +2% to +39% interval becomes 102–139 on its own index. No QJE percentage confidence interval is invented.</p>
    <h2>Evidence and authorship</h2>
    <p>Source checks, recommended wording, author reading, byline assent and publication permission are separate. The real edition retains pending author review. A production build refuses unapproved sources, exact uses or author/publication records. Preview access controls belong to the host; noindex does not authenticate visitors.</p>
    <p>Edition updated dates the page version. Each observation and source retains its own vintage and verification date. The finite freshness check is recorded with the evidence; it is not continuous coverage.</p>
    <details><summary>Qualitative profiles and earlier research</summary><p>The 31 staged profiles retain separate ordinal S1–S5 dimensions, missing selections, disagreement and provenance. They are not averaged or converted to the interaction’s inputs. Model-generated assessments display as “Analyst assessment · AI-assisted”; actual human review stays separate. Additional country coding, sector modules and probability forecasts remain outside this prototype.</p><p>Lineage records rw-007 and rw-012 were verified in the existing register on 27 August 2026; the BIS summary was reopened for this paragraph. <a href="https://github.com/yippy141/AI-Carrying-Capacity/blob/main/data/literature/related_work.csv">Related-work register</a> · <Link href="/lab">Research archive</Link>.</p></details>
    <p><Link href="/evidence">Sources and exact limitations</Link> · <Link href="/paper">Paper</Link></p>
  </main>;
}
