import Link from 'next/link';
import {loadStrategic} from '@/lib/strategicFutures';
import {editionMode} from '@/lib/readerEdition';
export const metadata={title:'Future assumptions and evidence'};
const edges=[['electricity_supply','compute_stock','Observed; interconnection and commissioning conditions'],['compute_stock','frontier_capability','Observed association; algorithms, data, talent, utilization'],['frontier_capability','software_process','Observed in bounded tasks; magnitude contested'],['frontier_capability','research_process','Observed in cases; magnitude unknown'],['software_process','robotics_technology','Partly observed; pace remains a hypothesis'],['robotics_technology','manufacturing_process','Early observed deployment; magnitude unknown'],['manufacturing_scale_and_learning','energy_equipment_cost','Historical analogy'],['advanced_manufacturing_capability','domestic_compute_hardware','Hypothesis; observed export-control constraints']];
export default function Assumptions(){const data=loadStrategic(editionMode());return <main id="main-content" className="reader-document strategic-sources" data-strategic-id="strategic-prototype-1" data-strategic-status={data.status}>
 <h1>What has to be true for this future?</h1><p className="document-intro">Four choices change the same rule-based construction. No country score, estimated growth curve or probability is hidden underneath it.</p><p>The richer chain is new scenario construction. It does not promote the accepted coupling records into observed compounded causality. All new exact uses remain drafts for review.</p>
 <h2>What kind of claim is this?</h2><dl className="knowledge-key"><dt>Observed or reported starting condition</dt><dd>A historical result, released artifact or policy document. Originating reports and official intentions retain those qualifications.</dd><dt>Inference</dt><dd>For example, cross-border specialization creates possible bargaining and disruption channels. The source does not measure the future geopolitical effect.</dd><dt>Scenario stipulation</dt><dd>The initial US-coalition lead, repeated feedback, diffusion ordering, validated redesign and political bargain are selected premises. Scenario time windows are illustrative.</dd><dt>Conditional rule output</dt><dd>The canvas and before/after table show what the authored rules imply if the premises hold. This is an executable qualitative branch explorer, not a calibrated simulation.</dd><dt>Forecast</dt><dd>A judgment about a resolvable event within a time window. AI 2027 and the external accounts below contain predictions. This prototype assigns no owner probability and activates no historical forecast. Its checkpoints are proposed observable tests, not author forecasts.</dd><dt>Value judgment</dt><dd>Choosing public missions or broad household benefit as a priority reflects a normative goal. The selector neither endorses a policy regime nor demonstrates that it works.</dd></dl>
 <h2>Every implemented assumption</h2>{data.controls.map(c=><section id={`rule-${c.key}`} key={c.key}><h3>{c.label}</h3><p>{c.rule}</p><p>{c.sourceIds.map((id,i)=><span key={id}>{i?' · ':''}<a href={`#${id}`}>{data.sources.find(s=>s.id===id)?.organization}</a></span>)}</p></section>)}<p>The settlement choice bundles ownership, procurement and investment assumptions for a readable prototype. These could come apart in reality. “Compact” with restricted diffusion means a limited-access agreement; broad access is not supplied automatically. Successful monitoring, continued participation and resource mobilization are premises, not consequences of signing a document.</p>
 <h2 id="source-trace">Selective source trace</h2><p>Verified 6 September 2026. Dates and versions below describe the sources, not a complete current-world census. Chinese policy is read in original Chinese; its English summary is AI-assisted and pending native-language human review.</p>{data.sources.slice(0,6).map(s=><article id={s.id} key={s.id} data-strategic-source={s.id} data-strategic-review={s.reviewStatus}><h3>{s.title}</h3><p><a href={s.url}>{s.organization}: original source</a> · {s.publicationDate??'Publication date not displayed'}</p><p><strong>Version / locator:</strong> {s.version}; {s.locator}.</p><p>{s.claim}</p><p><strong>Limit:</strong> {s.limit}</p><p className="figure-note">{s.reuse} Exact use: {s.reviewStatus}. Human review: {s.humanReview==='not_recorded'?'not recorded':'author reviewed'}. Translation: {s.translationReview.replaceAll('_',' ')}.</p></article>)}
 <h2 id="rival-accounts">Rival accounts, kept in their own terms</h2>{data.sources.slice(6).map(s=><article id={s.id} key={s.id} data-strategic-source={s.id} data-strategic-review={s.reviewStatus}><h3><a href={s.url}>{s.title}</a></h3><p>{s.claim}</p><p>{s.limit}</p><p className="figure-note">{s.version} · {s.locator} · checked {s.verifiedDate}; exact use {s.reviewStatus}.</p></article>)}
 <h2>The accepted records stay distinct</h2><p>The method’s external-scenario anchors remain AI 2027, AI 2040 Plan A, AI as Normal Technology and FINF baseline; the six-shared-premise cap remains. Citrini remains a staged stress-test candidate. The four new exploratory presets are not renamed versions or endorsements of those anchors. The historical crosswalk and earlier assumption browser are preserved.</p><details><summary>The eight accepted coupling dispositions</summary><div className="table-scroll"><table><caption>Summary of METHOD_PROFILES, not a new empirical graph</caption><thead><tr><th>From → to</th><th>Accepted boundary</th></tr></thead><tbody>{edges.map(([a,b,c])=><tr key={a+b}><td>{a.replaceAll('_',' ')} → {b.replaceAll('_',' ')}</td><td>{c}</td></tr>)}</tbody></table></div><p>Accepted empirical paths retain their second-order limit and equal edge widths. The flagship’s longer dashed paths are separately labelled scenario mechanisms, with no synthetic loop score.</p></details>
 <p><Link href="/">Return to the strategic study</Link> · <Link href="/work">Evidence from actual work</Link> · <Link href="/methods">Method and publication boundary</Link></p>
 </main>;}
