import Link from 'next/link';
import {loadReaderEdition} from '@/lib/readerEdition';
import {buildAdoptionDepthFigureModel} from '@/lib/adoptionDepth';
export const metadata={title:'Evidence'};
export default function Evidence(){
  const edition=loadReaderEdition();
  const model=buildAdoptionDepthFigureModel(edition.observations);
  const families=[{id:'adoption-ecb',title:'ECB SAFE: intensity',source:'src-0038',rows:model.ecb.rows,claims:['clm-0018','clm-0032']},{id:'adoption-census',title:'Census: reach and function breadth',source:'src-0048',rows:[model.btos.allFirms,...model.btos.adopterOnly],claims:['clm-0033','clm-0034','clm-0035']},{id:'adoption-eurostat',title:'Eurostat: adoption by firm size',source:'src-0042',rows:model.eurostat.sizeGradient,claims:['clm-0036']}];
  return <main className="reader-document" id="main-content"><h1>Follow a claim to its source.</h1><p className="document-intro">These are the finite claims used in this edition. A source being reviewed does not approve every sentence written from it. Observation periods, source checks and edition updates remain separate dates.</p>
    <nav className="reading-depths" aria-label="Evidence sections"><a href="#adoption-ecb">Reported use</a><a href="#reader-clm-qje">Measured work</a><a href="#reader-clm-tcv">Fusion</a></nav>
    {families.map(family=>{
      const source=edition.sources.find(s=>s.source_id===family.source)!;
      return <section key={family.id} id={family.id} className="evidence-entry"><h2>{family.title}</h2><p><a href={source.url_or_doi}>{source.title_english}</a> · {source.authors_org}</p><p className="figure-note">Source identity: {source.review_status}. Observation verification: {source.last_verified}. Claim dispositions retained from the existing ledger; no new human review is implied.</p>
        <div className="table-scroll" tabIndex={0} aria-label={`${family.title} observation table`}><table><caption>Reported measures, with original denominators</caption><thead><tr><th scope="col">Measure</th><th scope="col">Value</th><th scope="col">Period and denominator</th></tr></thead><tbody>{family.rows.map(row=><tr id={row.observation_id} key={row.observation_id}><th scope="row">{row.definition}<br/><span className="figure-note">{row.evidence_label==='model-estimate'?'Model estimate':row.evidence_label}</span></th><td>{row.value}%</td><td>{row.period}<br/>{row.denominator}<br/>{row.survey_universe}</td></tr>)}</tbody></table></div>
        {edition.adoptionClaims.filter(c=>family.claims.includes(c.claim_id)).map(c=><p className="essential-caveat" key={c.claim_id}>{c.caveat}</p>)}
        <details><summary>Machine records and reuse</summary><p>{family.rows.map(r=>r.observation_id).join(', ')} · {family.claims.join(', ')} · {source.source_id}</p><p>Manually reported facts in an original visualization; no raw survey microdata or publisher figures redistributed. Attribution retained. Eurostat is not responsible for this adapted presentation.</p><p><a href="/reader/adoption.csv" download>Download the plotted adoption records (CSV)</a></p></details>
      </section>;
    })}
    <section className="evidence-entry" id="nbs-restriction"><h2>NBS: context and translation boundary</h2><p>The original Chinese-language source is retained for context. Its different enterprise universe does not support an all-firm comparison. The numeric record is unplotted and load-bearing translated wording remains pending native-language human review.</p><p><a href={edition.sources.find(s=>s.source_id==='src-0049')!.url_or_doi}>NBS Fifth National Economic Census — original source</a></p><p className="figure-note">Record: src-0049 / clm-0037 / obs-adoption-depth-013. Agent language verification is recorded; a human reviewer is not recorded as completed.</p></section>
    {edition.uses.map(use=><section className="evidence-entry" id={use.id} key={use.id} data-claim-id={use.id} data-use-status={use.status}><h2>{use.panel}: {use.title.toLowerCase()}</h2><p className="edition-note">{use.displayReview}</p><p>{use.claim}</p><dl className="evidence-details">{Object.entries({Measurement:`${use.value===null?'No numeric plant estimate':`${use.value} ${use.unit}`}. ${use.comparison}`,Population:use.sample,'Tool and period':`${use.tools}. ${use.period}`,Design:use.design,Uncertainty:use.uncertainty,Quality:use.quality,'Transfer limit':use.caveat,Locator:use.locator,'Actual review':use.reviewer,'What would change this':use.revisit}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
      {use.sources.map(source=><p key={source.source_id}><a href={source.url_or_doi}>{source.title_english}</a><br/><span className="figure-note">Published {source.publication_date} · registered source status: {source.review_status} · source record last verified {source.last_verified}. This exact use checked {use.verificationDate}.</span></p>)}
      <details><summary>Use restrictions and linked records</summary><p>{use.restrictions.join(' ')}</p><p>{use.license.license_name}. This edition uses original paraphrases of reported facts. No paper, raw dataset or publisher figure is redistributed. Commercial QJE reuse requires separate review.</p><p>Translation: {use.translation.replaceAll('_',' ')}. Human review: {use.humanReview.replaceAll('_',' ')}. {use.companyOrTarget.replaceAll('_',' ')}.</p><p>{use.id} · {use.sourceIds.join(', ')}{use.legacyClaimIds.length?` · historical staged claim ${use.legacyClaimIds.join(', ')}`:''}</p></details>
    </section>)}
    <section className="evidence-entry"><h2>Interpretations and scenarios</h2><p>The argument about workflow dependencies, transfer and who captures value is an interpretation. It is not a measured national effect. Figure 3 is a scenario demonstration with invented inputs; its outputs are conditional arithmetic. The fusion trace distinguishes the observed control result from evidence needed for a broader conclusion.</p><p>The 31 staged structural profiles preserve model submissions, ranges, disagreements and review history outside the reading path. They supply no values to the mechanism interaction.</p><p><Link href="/methods">Read the method and omissions</Link></p></section>
  </main>;
}
